// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /stats/categories` — one row of the (category, subcategory) breakdown.
 */
export type CategoryCount = { category: string, subcategory: string, count: number, };
