// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactedEntry } from "./RedactedEntry";

/**
 * One event on the proxy event bus.
 */
export type ProxyEvent = { "type": "Request", id: string, ts: string, method: string, uri: string, redacted: Array<RedactedEntry>, } | { "type": "Response", id: string, ts: string, uri: string, status: number, };
