// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One redaction the proxy applied to a body.
 *
 * Security note: `fake_value` is the substituted value (safe to display
 * or log). The original matched bytes are NEVER on this struct — they
 * stay only in the on-disk JSONL audit log.
 */
export type RedactedEntry = { rule_id: string, category: string, subcategory: string, severity: string, original: string, fake_value: string, };
