// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactedRow } from "./RedactedRow";

/**
 * `GET /redactions` envelope — caller gets a page and the cursor to continue.
 */
export type RedactedPage = { rows: Array<RedactedRow>, 
/**
 * pass back as `?cursor=` to fetch the next page. `null` when exhausted.
 */
next_cursor: string | null, };
