// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /redactions?…` — one row of the full per-redaction drill-down.
 * Carries the secret half (`original`, `fake_value`) so this endpoint must
 * remain loopback-only (see `src/stats/mod.rs` doc comment).
 */
export type RedactedRow = { 
/**
 * monotonically increasing row id from the redactions table — also serves as the pagination cursor
 */
id: number, 
/**
 * unix epoch seconds
 */
ts: number, rule_id: string, category: string, subcategory: string, severity: string, 
/**
 * "request" | "response"
 */
direction: string, request_id: string, original: string, fake_value: string, };
