// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /stats/rules?limit=N` — one row of the rule-level breakdown.
 */
export type RuleCount = { rule_id: string, count: number, };
