// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /stats` — aggregated counts for the dashboard summary card.
 */
export type Summary = { total: number, last_24h: number, last_7d: number, last_30d: number, };
