// runtime pattern statics — loaded from combined.yaml at compile time
// combined.yaml is generated by build.rs from vendored upstream sources

use std::sync::{Arc, LazyLock};

use aho_corasick::AhoCorasick;
use rayon::prelude::*;
use regex::bytes::Regex;

use crate::types::rule::NormalizedRule;

/// License attributions for embedded pattern sources. See THIRD-PARTY-NOTICES.md
/// for the authoritative list; secrets-patterns-db is CC BY-SA 4.0 (ShareAlike).
pub const ATTRIBUTION: &str = "\
Pattern sources:\n\
- secrets-patterns-db (CC BY-SA 4.0)\n\
  Author: Mazin Ahmed / secrets-patterns-db contributors\n\
  License: Creative Commons Attribution-ShareAlike 4.0 (CC BY-SA 4.0)\n\
  URL: https://github.com/mazen160/secrets-patterns-db\n\
- gitleaks (MIT): https://github.com/gitleaks/gitleaks\n\
- nosey-parker (Apache-2.0): https://github.com/praetorian-inc/noseyparker\n\
- detect-secrets (Apache-2.0): https://github.com/Yelp/detect-secrets";

/// wrapper to deserialize combined.yaml which has a `rules:` top-level key
#[derive(serde::Deserialize)]
struct CombinedYaml {
    rules: Vec<NormalizedRule>,
}

/// Embedded full ruleset — used as default when no env override is set.
const EMBEDDED_RULES_YAML: &str = include_str!("../../rules/combined.yaml");

/// All normalized rules.
///
/// Source priority (first that resolves wins):
///   1. `BLEEP_RULES_FILE` env var → reads YAML from that path at runtime
///      (used for dev mode: e.g. `rules/combined-100.yaml` for fast startup)
///   2. embedded `rules/combined.yaml` (the full 401-rule set, baked in at compile)
///
/// On override-load failure (file missing, malformed) we panic — better to
/// fail loud than silently serve a different ruleset than the user expects.
pub static NORMALIZED_RULES: LazyLock<Vec<NormalizedRule>> = LazyLock::new(|| {
    let yaml: std::borrow::Cow<'static, str> = match std::env::var("BLEEP_RULES_FILE") {
        Ok(path) if !path.is_empty() => {
            let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("BLEEP_RULES_FILE={path} could not be read: {e}")
            });
            eprintln!("[patterns] using rules from {path} (BLEEP_RULES_FILE)");
            std::borrow::Cow::Owned(content)
        }
        _ => std::borrow::Cow::Borrowed(EMBEDDED_RULES_YAML),
    };
    let parsed: CombinedYaml = serde_yml::from_str(&yaml)
        .expect("rules YAML must be valid (BLEEP_RULES_FILE or embedded combined.yaml)");
    parsed.rules
});

/// AhoCorasick automaton built from all rule keywords for fast pre-filter
pub static COMBINED: LazyLock<AhoCorasick> = LazyLock::new(|| {
    let keywords: Vec<&str> = NORMALIZED_RULES
        .iter()
        .flat_map(|r| r.keywords.iter().map(|k| k.as_str()))
        .collect();
    AhoCorasick::new(keywords).expect("AhoCorasick build failed")
});

/// compiled regex per rule, paired with Arc<NormalizedRule> and an optional exclusion regex.
///
/// tuple layout: (rule, main_re, exclude_re)
/// exclude_re is compiled from NormalizedRule::exclude_regex when present; a match on the
/// raw matched bytes causes the detection to be discarded before recording.
///
/// uses the same size limits as build.rs validation (256 MB DFA) so that any regex
/// that passed validation at compile time also compiles at runtime.
/// POSIX (?# ... ) comments are stripped before compilation — combined.yaml may retain
/// them in (?x) verbose patterns; Rust regex supports only # line comments in (?x) mode.
pub static RULES: LazyLock<Vec<(Arc<NormalizedRule>, Regex, Option<Regex>)>> = LazyLock::new(|| {
    NORMALIZED_RULES
        .par_iter()
        .map(|r| {
            let cleaned = strip_posix_comments(&r.regex);
            let re = regex::bytes::RegexBuilder::new(&cleaned)
                .size_limit(256 * 1024 * 1024)
                .dfa_size_limit(256 * 1024 * 1024)
                .build()
                .unwrap_or_else(|e| {
                    panic!("regex compile failed for rule '{}': {}", r.id, e)
                });
            let excl_re = r.exclude_regex.as_deref().map(|pat| {
                regex::bytes::Regex::new(pat).unwrap_or_else(|e| {
                    panic!("exclude_regex compile failed for rule '{}': {}", r.id, e)
                })
            });
            (Arc::new(r.clone()), re, excl_re)
        })
        .collect()
});

/// strip POSIX-style inline comments (?# ... ) from a regex string
///
/// the Rust regex crate does not support (?# ...) comment syntax — only (?x) # line comments.
/// these appear in some NP patterns inside (?x) verbose blocks.
fn strip_posix_comments(pattern: &str) -> String {
    let mut result = String::with_capacity(pattern.len());
    let bytes = pattern.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if i + 2 < bytes.len()
            && bytes[i] == b'('
            && bytes[i + 1] == b'?'
            && bytes[i + 2] == b'#'
        {
            // skip until the closing ')'
            i += 3;
            let mut depth = 1;
            while i < bytes.len() && depth > 0 {
                if bytes[i] == b'(' {
                    depth += 1;
                } else if bytes[i] == b')' {
                    depth -= 1;
                }
                i += 1;
            }
        } else {
            result.push(bytes[i] as char);
            i += 1;
        }
    }
    result
}

pub fn get_rules() -> &'static Vec<(Arc<NormalizedRule>, Regex, Option<Regex>)> {
    &RULES
}

pub fn get_combined() -> &'static AhoCorasick {
    &COMBINED
}

pub fn get_normalized_rules() -> &'static Vec<NormalizedRule> {
    &NORMALIZED_RULES
}
