// runtime pattern statics — loaded from combined.yaml at compile time
// combined.yaml is generated by build.rs from vendored upstream sources

use std::sync::{Arc, LazyLock};

use aho_corasick::AhoCorasick;
use regex::bytes::Regex;

use crate::types::rule::NormalizedRule;

/// CC-BY 4.0 and other license attributions for embedded pattern sources
pub const ATTRIBUTION: &str = "\
Pattern sources:\n\
- secrets-patterns-db (CC-BY 4.0)\n\
  Author: Mazin Ahmed / secrets-patterns-db contributors\n\
  License: Creative Commons Attribution 4.0 (CC-BY 4.0)\n\
  URL: https://github.com/mazen160/secrets-patterns-db\n\
- gitleaks (MIT): https://github.com/gitleaks/gitleaks\n\
- nosey-parker (Apache-2.0): https://github.com/praetorian-inc/noseyparker";

/// wrapper to deserialize combined.yaml which has a `rules:` top-level key
#[derive(serde::Deserialize)]
struct CombinedYaml {
    rules: Vec<NormalizedRule>,
}

/// all normalized rules embedded from combined.yaml at compile time
pub static NORMALIZED_RULES: LazyLock<Vec<NormalizedRule>> = LazyLock::new(|| {
    let parsed: CombinedYaml =
        serde_yml::from_str(include_str!("../../rules/combined.yaml"))
            .expect("combined.yaml embedded at build time must be valid YAML");
    parsed.rules
});

/// AhoCorasick automaton built from all rule keywords for fast pre-filter
pub static COMBINED: LazyLock<AhoCorasick> = LazyLock::new(|| {
    let keywords: Vec<&str> = NORMALIZED_RULES
        .iter()
        .flat_map(|r| r.keywords.iter().map(|k| k.as_str()))
        .collect();
    AhoCorasick::new(keywords).expect("AhoCorasick build failed")
});

/// compiled regex per rule, paired with Arc<NormalizedRule> for zero-copy sharing
pub static RULES: LazyLock<Vec<(Arc<NormalizedRule>, Regex)>> = LazyLock::new(|| {
    NORMALIZED_RULES
        .iter()
        .map(|r| {
            let re = regex::bytes::Regex::new(&r.regex)
                .expect("regex pre-validated by build.rs");
            (Arc::new(r.clone()), re)
        })
        .collect()
});

pub fn get_rules() -> &'static Vec<(Arc<NormalizedRule>, Regex)> {
    &RULES
}

pub fn get_combined() -> &'static AhoCorasick {
    &COMBINED
}

pub fn get_normalized_rules() -> &'static Vec<NormalizedRule> {
    &NORMALIZED_RULES
}
