// runtime pattern statics — loaded from combined.yaml at compile time
// combined.yaml is generated by build.rs from vendored upstream sources

use std::sync::{Arc, LazyLock};

use aho_corasick::AhoCorasick;
use regex::bytes::Regex;

use crate::types::rule::NormalizedRule;

/// CC-BY 4.0 and other license attributions for embedded pattern sources
pub const ATTRIBUTION: &str = "\
Pattern sources:\n\
- secrets-patterns-db (CC-BY 4.0)\n\
  Author: Mazin Ahmed / secrets-patterns-db contributors\n\
  License: Creative Commons Attribution 4.0 (CC-BY 4.0)\n\
  URL: https://github.com/mazen160/secrets-patterns-db\n\
- gitleaks (MIT): https://github.com/gitleaks/gitleaks\n\
- nosey-parker (Apache-2.0): https://github.com/praetorian-inc/noseyparker";

/// wrapper to deserialize combined.yaml which has a `rules:` top-level key
#[derive(serde::Deserialize)]
struct CombinedYaml {
    rules: Vec<NormalizedRule>,
}

/// all normalized rules embedded from combined.yaml at compile time
pub static NORMALIZED_RULES: LazyLock<Vec<NormalizedRule>> = LazyLock::new(|| {
    let parsed: CombinedYaml =
        serde_yml::from_str(include_str!("../../rules/combined.yaml"))
            .expect("combined.yaml embedded at build time must be valid YAML");
    parsed.rules
});

/// AhoCorasick automaton built from all rule keywords for fast pre-filter
pub static COMBINED: LazyLock<AhoCorasick> = LazyLock::new(|| {
    let keywords: Vec<&str> = NORMALIZED_RULES
        .iter()
        .flat_map(|r| r.keywords.iter().map(|k| k.as_str()))
        .collect();
    AhoCorasick::new(keywords).expect("AhoCorasick build failed")
});

/// compiled regex per rule, paired with Arc<NormalizedRule> for zero-copy sharing
///
/// uses the same size limits as build.rs validation (256 MB DFA) so that any regex
/// that passed validation at compile time also compiles at runtime.
/// POSIX (?# ... ) comments are stripped before compilation — combined.yaml may retain
/// them in (?x) verbose patterns; Rust regex supports only # line comments in (?x) mode.
pub static RULES: LazyLock<Vec<(Arc<NormalizedRule>, Regex)>> = LazyLock::new(|| {
    NORMALIZED_RULES
        .iter()
        .map(|r| {
            let cleaned = strip_posix_comments(&r.regex);
            let re = regex::bytes::RegexBuilder::new(&cleaned)
                .size_limit(256 * 1024 * 1024)
                .dfa_size_limit(256 * 1024 * 1024)
                .build()
                .unwrap_or_else(|e| {
                    panic!("regex compile failed for rule '{}': {}", r.id, e)
                });
            (Arc::new(r.clone()), re)
        })
        .collect()
});

/// strip POSIX-style inline comments (?# ... ) from a regex string
///
/// the Rust regex crate does not support (?# ...) comment syntax — only (?x) # line comments.
/// these appear in some NP patterns inside (?x) verbose blocks.
fn strip_posix_comments(pattern: &str) -> String {
    let mut result = String::with_capacity(pattern.len());
    let bytes = pattern.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if i + 2 < bytes.len()
            && bytes[i] == b'('
            && bytes[i + 1] == b'?'
            && bytes[i + 2] == b'#'
        {
            // skip until the closing ')'
            i += 3;
            let mut depth = 1;
            while i < bytes.len() && depth > 0 {
                if bytes[i] == b'(' {
                    depth += 1;
                } else if bytes[i] == b')' {
                    depth -= 1;
                }
                i += 1;
            }
        } else {
            result.push(bytes[i] as char);
            i += 1;
        }
    }
    result
}

pub fn get_rules() -> &'static Vec<(Arc<NormalizedRule>, Regex)> {
    &RULES
}

pub fn get_combined() -> &'static AhoCorasick {
    &COMBINED
}

pub fn get_normalized_rules() -> &'static Vec<NormalizedRule> {
    &NORMALIZED_RULES
}
